### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by a7ypically** [apankrat/dnswhisperer#1]
Hi,

Thanks for this code. I plan to use it to filter AAAA queries as I don't have ipv6 and it's just a waste as all clients do ask for ipv6 addresses.

Looking at the code I think I see a few issues:
- When iterating requests, if one request has multiple queries in it, you do iterate all of them but as soon as one matches a filter you set nope_it to true and then all the rest of the queries in that request will be filtered though I assume they may have other names in them.
- When you do filter a request, why do you send the request to the real server instead of immediately sending a response to the client that it is not found?
- There is no overflow handling in the pending requests array. So if the server gets more requests than the size of the array it will overrun the first requests and the clients will not get a response. I think it's better to track the current number of pending requests and if there's an overflow print a warning and drop the new request.

Anyway, this is very useful for me so thanks a lot for sharing your code!

**Comment by apankrat** [comment]
The code is as rudimentary as it is, basically, _lazy_.

It doesn't want to deal with DNS packet generation, which is why it passes all queries to the real server, so that the server would create a reply and then the daemon would then just patch it.

Re: queue management and your suggestion - consider what would happen when the queue gets  filled because _responses_ from the server are not received.

PS. And thanks for the kudos :)
PPS. Have a look at [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html), I suspect it can do what you want.
